name = "PPInterpolation"
uuid = "0bf8acf5-7f56-4370-abee-dfc0c3b7d49e"
authors = ["Jherek Healy <jherekhealy@protonmail.com>"]
version = "0.2.0"

[deps]
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ForwardDiff = "0.10"
Cbc = "0.9"
JuMP = "0.22"
julia = 1
